### ISSUE TITLE
Errors in check_repos_available

### ISSUE THREAD

**Issue by wfulp** [sellorm/envstat#2]
Thanks for writing this package. It's super helpful making sure everything is all set up regardless of running locally or in R Workbench. 

I am running into an error when I have more than 1 repo.

``` r
    my_repos <- c(
      "CRAN Mirror" = "http://pm.rdcloud.foobar.com:XXXX/prod-cran/latest",
      "BioConductor Mirror" = "http://pm.rdcloud.foobar.com:XXXX/bioconductor-local/latest",
      "Foobar RSPM" = "http://pm.rdcloud.foobar.com:XXXX/bms-cg-biogit-bran/latest"
    )
    options(repos = my_repos)
    envstat:::check_repos_available(list(repos_available = TRUE))
#> 
#> ── Checking configured repos are available ──
#> 
#> Error in if (repo == "@CRAN@") {: the condition has length > 1
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>    
    
The issue for me seems to be in the line: `for (repo in options("repos"))`.
 If I change it to `for (repo in options("repos")$repos)` it works (until I get to the below error).

I am also running into a different error even when 1 repo.

``` r
    my_repos <- c("CRAN Mirror" = "http://pm.rdcloud.foobar.com:XXXX/prod-cran/latest")
    options(repos = my_repos)
    envstat:::check_repos_available(list(repos_available = TRUE))
#> ── Checking configured repos are available ──
#> Error in if (result$status_code == 200) {: argument is of length zero
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sellorm** [comment]
Thanks for finding this bug for me Jimmy, much appreciated!

The second error you've highlighted appears to be specific to RStudio Package Manager because the test strategy I adopted for CRAN repos, only works on vanilla mirrors, not in the RSPM world.

I have a couple of ideas about how to fix that, but I'll need some time to test them.

**Comment by sellorm** [comment]
Hi again Jimmy, if you have a moment, could you run the dev version of the package from github and see if the problems are fixed?

```
devtools::install_github("sellorm/envstat")
```

I'll reopen if there are still issues, but if not I'll prepare a new CRAN release.

**Comment by wfulp** [comment]
Thanks for the quick fix. It's mostly fixed now, but if I put in a bad repo I get an error instead of a failed test (5th repo in example). Also if I put in a bad link to the repo but the correct server it still says CRAN repo available (4th repo in example).

```
    my_repos <- c(
      "BMS CRAN mirror" = "pm.rdcloud.foobar.com:XXXX/prod-cran/latest",
      "BMS BioConductor mirror" = "http://pm.rdcloud.foobar.com:XXXX/bioconductor-local/latest",
      "BMS RSPM" = "http://pm.rdcloud.foobar.com:XXXX/bms-cg-biogit-bran/latest",
      "Foobar Server Bad Name" = "http://pm.rdcloud.foobar.com:XXXX/mistyped_link/latest",
      "Bad Repo" = "http://mistyped_link/bms-cg-biogit-bran/latest"
    )
    options(repos = my_repos)
    envstat:::check_repos_available(list(repos_available = TRUE))
#> 
#> ── Checking configured repos are available ──
#> 
#> ✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXX/prod-cran/latest
#> ✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXXbioconductor-local/latest
#> ✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXX/bms-cg-biogit-bran/latest
#> ✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXX/mistyped_link/latest
#> Error in if (httr2::resp_headers(result)$`x-repository-type` == "RSPM") {: argument is of length zero
```

**Comment by sellorm** [comment]
Hmm, this part of the validation is messier than I'd given it credit for. Huge thanks for taking the time to work through these examples.

The way that I originally chose to validate vanilla CRAN mirrors was to check for the existence of a particular file that I know is hosted there. RSPM does not host that same file, hence the original errors.

I tried to fix it by checking to see if the server is RSPM in situations when the file is missing, but that will incorrectly report a pass in the event of a mistyped URL. 

So it looks like a quick fix is off the table. I'll have to go back to the drawing board and come up with something better.

**Comment by sellorm** [comment]
Hi again Jimmy. I had another think about it and I think I may have overcomplicated things with my previous attempt to fix this. Could you try it again and let me know where we are - TIA!

**Comment by wfulp** [comment]
It's behaving exactly as I would expect now. I don't know if you want to call it all `CRAN repo`, but that's super minor text suggestion. Thank you so much for getting this working perfectly.

```
[develop] >     envstat:::check_repos_available(list(repos_available = TRUE))

── Checking configured repos are available ──

✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXX/prod-cran/latest
✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXX/bioconductor-local/latest
✔ CRAN repo available: http://pm.rdcloud.foobar.com:XXXX/bms-cg-biogit-bran/latest
✖ Error contacting CRAN repo: http://pm.rdcloud.foobar.com:XXXX/mistyped_link/latest
✖ Error contacting CRAN repo: http://mistyped_link/bms-cg-biogit-bran/latest
[1]  TRUE  TRUE  TRUE FALSE FALSE
```

**Comment by sellorm** [comment]
That's great news!

Do you mean that it should be `CRAN repo available` and `CRAN repo unavailable`?

**Comment by wfulp** [comment]
No I mean referring the to Bioconductor mirror as "CRAN repo" seems weird. Maybe just drop the word "CRAN" now that it is more generally checking repos. Sorry in advance if I'm messing up the nomenclature.

**Comment by sellorm** [comment]
Got it, thanks. I've just pushed another commit that changes the wording to be slightly less CRAN-specific.

Anyway, thanks again for reporting this and helping me work through the solution. I'll prepare a release for CRAN as soon as I can.

**Comment by sellorm** [comment]
New version is on it's way to CRAN - should be available shortly.
